version: "3.8"
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: accounts_server
    networks: 
      - node-network
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file: .env
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: accounts_client
    networks: 
      - node-network
    ports:
      - '5173:5173'
    volumes: 
      - ./client:/usr/src/app
      - /app/node_modules
    stdin_open: true
  nginx:
    build: 
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - node-network
    depends_on:
       - server
       - client
networks: 
  node-network:
    driver: bridge